# <span style='color:black'> <center>Trabajando datos con Numpy</center> </span>
## 1. Numpy Arrays
<p><img src="https://www.ucatalunya.edu.co/img/blog/herramientas-de-analisis-de-datos.jpg" width="850"</p>

# La librería de Numpy

Numpy es una de las librería más utilizadas dentro de python, utilizada para cálculo numérico y análisis de datos. Una de sus características principales es el poder manejar un gran volumen de datos.
- Herramientas lectura y escritura de datos matriciales.
- Funciones matemáticas que realizan operaciones sobre la data dentro de un arreglo sin nececidad de utilizar iteradores.
- Capacidades para trabajar temas de álgebra lineal y generación de números aleatorios.

## Objetos multidimensionales de Numpy

Los **arrays** son objetos caracterísitcos de **Numpy**, los cuales son una manera rápida y flexible de contener grandes cantidades de datos dentro de Python. Los **arrays** permiten realizar operaciones matemáticas por bloque usando una sintaxis simliar a como se realizan operaciones entre escalares.

Para crear un arreglo n-dimensional, necesitamos importar la librería **Numpy** y utilizar la función *array*.

In [ ]:
import math

In [3]:
import matplotlib

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

        The result is between 0 and pi.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

        The result is between -pi/2 and pi/2.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    cbrt(x, /)
        Return the cube root of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This i

In [4]:
#importar la libreria numpy
import numpy as np

#crear un array dentro de una variable
datos = np.array([[1,-2,-3],[0,1,5]])


#observamos el array
print(datos)



[[ 1 -2 -3]
 [ 0  1  5]]


Otra forma de definir un array es a partir de una o varias listas.

In [6]:
#Crear un array unidimensional a partir de una lista
mi_lista = [2,4,6,8,10,12]
mi_arreglo = np.array(mi_lista)
print(mi_arreglo)
type(mi_arreglo)

[ 2  4  6  8 10 12]


numpy.ndarray

In [7]:
#Crear un array bidimensional a partir de varias listas
lista1 = [5, 10, 15, 20]
lista2= [6, 12, 18, 24]
lista3= [7, 14, 21, 28]
mi_lista2= [lista1, lista2, lista3]
mi_arreglo2= np.array(mi_lista2)
print(mi_arreglo2)


[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]]


In [9]:
lista1 = [5, 10, 15, 20]
lista2= [6, 12, 18, 24]
lista3= [7, 14, 21, 28]
mi_arregloo2= np.array([lista1, lista2, lista3])
print(mi_arregloo2)

[[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]]


### Propiedades de los arrays

Podemos conocer ciertas propiedades de los numpy arrays.
- **shape:** devuelve la forma de un array (el número de elementos en cada dimensión).
- **ndim:** devuelve el número de dimensiones que tiene un array.
- **size:**  devuelve el conteo de elemento dentro de un array.
- **dtype:** devuelve el tipo de dato contenido dentro del array.

In [14]:
#Forma de un numpy array
print(mi_arreglo2.shape)

#Dimensión de un numpy array
print(mi_arreglo2.ndim)

#Tipo de dato dentro de un numpy array
print(mi_arreglo2.dtype)

#Tamaño de un numpy array
print(mi_arreglo2.size)

#bytes por elemento
print(mi_arreglo2.itemsize)

(3, 4)
2
int64
12
8


El tipo de dato dentro puede definirse a la hora de construir el array.

In [15]:
mi_arreglo3 = np.array(mi_lista2, dtype=np.int16)
print(mi_arreglo3.dtype)

int16


Es posible crear numpy arrays vacios o llenos de 0 para crear un objeto que será editado posteriormente.

In [16]:
#numpy arrays que contiene 0 en todas las entradas
array_ceros = np.zeros((2,2))
print(array_ceros)

[[0. 0.]
 [0. 0.]]


In [17]:
#numpy arrays que contiene 1 en todas las entradas
array_unos=np.ones((3,3))
print(array_unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#numpy arrays vacio
array_vacios = np.empty((3,2))
print(array_vacios)

[[ 1.79769313e+308 -1.79769313e+308]
 [ 2.00000000e+000  2.22044605e-016]
 [ 2.22507386e-308  4.94065646e-324]]


### Arrays que contienen secuencias de números

Los métodos **arange** y **linspace** se pueden utilizar para crear arreglos a partir de secuencias de valores.

- **arange**: genera un conjunto de números entre un valor de inicio y uno final, pudiendo especificar un incremento entre los valores.
- **linspace**: genera un array NumPy formado por n números equiespaciados entre dos dados

In [20]:
# array de una secuencia de 20 números con forma 4x5
np.arange(20).reshape(4,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
# array de 50 números entre 10 y 20
np.linspace(10,20,50)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

## Operando arrays

Podemos utilizar los operadores aritméticos para realizar operaciones sobre los numpy arrays.

In [23]:
# sumando y multiplicando un escalar a un array
data = np.linspace(15,25,11)
print(data+10)
print(data*3)

[25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.]
[45. 48. 51. 54. 57. 60. 63. 66. 69. 72. 75.]


In [24]:
# sumando 2 arrays (la suma se hará entrada a entrada)
data2=np.arange(10,30,2)
data3=np.arange(30,40,1)
print(data2)
print(data3)
print(data2+data3)

[10 12 14 16 18 20 22 24 26 28]
[30 31 32 33 34 35 36 37 38 39]
[40 43 46 49 52 55 58 61 64 67]


In [25]:
# multiplicando 2 arrays (la multiplicación se hará entrada a entrada)
data2=np.arange(10,30,2)
data3=np.arange(30,40,1)
print(data2)
print(data3)
print(data2*data3)


[10 12 14 16 18 20 22 24 26 28]
[30 31 32 33 34 35 36 37 38 39]
[ 300  372  448  528  612  700  792  888  988 1092]


In [26]:
# producto punto 2 arrays 
data2=np.arange(10,30,2)
data3=np.arange(30,40,1)
print(data2)
print(data3)
print(np.dot(data2,data3))

[10 12 14 16 18 20 22 24 26 28]
[30 31 32 33 34 35 36 37 38 39]
6720


In [27]:
# producto cruz 2 arrays 

#(a1, a2, a3) X (b1, b2, b3) = (a2*b3 - a3*b2, a3*b1 - a1*b3, a1*b2 - a2*b1)

data2 = np.array([2,6,9])
data3 = np.array([4,5,6])
print(np.cross(data2,data3))

[ -9  24 -14]
